services:
  bahasa-beraja:
    build: .
    ports:
      - "80:3000"
    container_name: bahasa-beraja-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    networks:
      - tools_network
    volumes:
      - ./:/app
      - /app/node_modules
    command: npm start

networks:
  tools_network:
    external: true 