services:
  pimi-bahasa:
    build: .
    ports:
      - "80:3000"
    container_name: pimi-bahasa-app
    restart: unless-stopped
    environment:
      - NODE_ENV=development
    networks:
      - tools_network
    volumes:
      - ./:/app
    command: npm start

networks:
  tools_network:
    external: true 