services:
  bahasa-beraja:
    build: .
    ports:
      - "2999:80"
    container_name: bahasa-beraja-app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - tools_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

networks:
  tools_network:
    external: true 