version: '3.8'

services:
  bahasa-app:
    build: .
    container_name: bahasa-app
    restart: always
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://31.97.66.59:3000
      - DATABASE_URL=postgresql://admin:admin@31.97.66.59:5432/dify
      - REDIS_URL=redis://default:admin@31.97.66.59:6379/0
      - TZ=Asia/Shanghai
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - bahasa_network

networks:
  bahasa_network:
    external: true
    name: tools_network

volumes:
  bahasa_postgres_data: 