services:
  bahasa-beraja-test:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "2999:80"
    container_name: bahasa-beraja-test
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - REACT_APP_ENV=test
    networks:
      - test_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    labels:
      - "traefik.enable=false"  # 确保不被生产环境代理
      - "environment=test"

networks:
  test_network:
    driver: bridge
    name: bahasa-test-network 